#!/bin/bash
JRM_DIR=$(dirname $(readlink -f $0))
echo "initializing script..."
sleep 1
echo "script started from $JRM_DIR"
sleep 1
echo "checking for dependencies..."
sleep 2
if [[ ! -f $JRM_DIR/env/pkg_list.txt ]]; then 
		echo "script cannot find ./env/pkg_list.txt! exiting..." 
		echo "make sure ./init is run from the base of the git repository."
		exit
else 
		echo "found /env folder with package list! let's continue..."
fi 

echo "By default, the script will create a directory at $HOME/gits."
echo "Enter an alternative git directory, or simply press [Enter] to continue using default..."
read JRM_GIT_DIR
if [[ -z $JRM_GIT_DIR ]]; then
JRM_GIT_DIR=$HOME/gits
fi 
# exp_user=$1
# exp_pass=$2
JRM_ARCH=$(uname -m)

echo -n "

 ██████╗  ███████╗  ██████╗  █████╗  ██╗   ██╗ ███████╗ ███████╗
 ██╔══██╗ ██╔════╝ ██╔════╝ ██╔══██╗ ██║   ██║ ██╔════╝ ██╔════╝
 ██████╔╝ █████╗   ██║      ███████║ ██║   ██║ ███████╗ █████╗
 ██╔══██╗ ██╔══╝   ██║      ██╔══██║ ██║   ██║ ╚════██║ ██╔══╝
 ██████╔╝ ███████╗ ╚██████╗ ██║  ██║ ╚██████╔╝ ███████║ ███████╗
 ╚═════╝  ╚══════╝  ╚═════╝ ╚═╝  ╚═╝  ╚═════╝  ╚══════╝ ╚══════╝"

 echo -n "
 
 ████████╗ ██╗  ██╗ ███████╗     ███╗   ██╗ ███████╗ ████████╗
 ╚══██╔══╝ ██║  ██║ ██╔════╝     ████╗  ██║ ██╔════╝ ╚══██╔══╝
    ██║    ███████║ █████╗       ██╔██╗ ██║ █████╗      ██║
    ██║    ██╔══██║ ██╔══╝       ██║╚██╗██║ ██╔══╝      ██║
    ██║    ██║  ██║ ███████╗ ██╗ ██║ ╚████║ ███████╗    ██║
    ╚═╝    ╚═╝  ╚═╝ ╚══════╝ ╚═╝ ╚═╝  ╚═══╝ ╚══════╝    ╚═╝"
echo " "
sleep 1
clear
echo "alright, let's proceed."
sleep 1
echo "--------------------------------------- "
echo "     █         █                 █  █   "
echo "     █                    █      █  █   "
echo " ███ █ █ ███   █ ███ ███ ███ ███ █  █   "
echo " █ █ ██  █ █   █ █ █ █    █    █ █  █   "
echo " █ █ ██  █ █   █ █ █   █  █  ███ █  █   "
echo " ███ █ █ ███   █ █ █ ███  ██ ███ ██ ██  "
echo " █         █                            "
echo " █       ███   update & install         "
echo "--------------------------------------- "
sleep 3
sudo apt update && sudo apt upgrade -y
sleep 1
echo "installing Zshell, git, and important development packages"
sudo apt install -y zsh expect git curl wget vim dialog dpkg pkg-config build-essential neofetch htop nmon nmap pinentry-tty htop devscripts 
sleep 1
echo "installing important libraries..."
sudo xargs -a lib_list.txt apt install -y
sleep 1 
echo "installing useful packages..."
sudo xargs -a pkg_list.txt apt install -y
sleep 1
echo " "
echo "packages installed!"

echo "setting up dev environment..."
sleep 3

echo "installing Golang to /usr/local/go..."

# go binaries for x86, arm64, arm7
JRM_GO_LINUX=go1.14.6.linux-amd64.tar.gz
JRM_GO_ARM64=go1.14.6.linux-arm64.tar.gz
JRM_GO_ARM7=

# determine computer cpu arch and grab correct binary
if [[ $JRM_ARCH == "aarch64" ]]; then
    cd $JRM_DIR && wget https://golang.org/dl/$JRM_GO_ARM64
fi

if [[ $JRM_ARCH == "x86_64" ]]; then
    cd $JRM_DIR && wget https://golang.org/dl/$JRM_GO_LINUX 
fi 

# unzip to /go and install
tar -xvf $JRM_GO
sudo mv $JRM_DIR/go /usr/local
echo "creating binary and source Go directory in $HOME..."
mkdir -p $HOME/go
echo "Golang has been installed!" 
sleep 1
echo "installing nodejs version manager in /usr/local/..."
sleep 1
echo "creating $HOME/gits and downloading n build files..."
mkdir -p $JRM_DIR_GIT && cd $JRM_DIR_GIT
git clone https://github.com/tj/n $JRM_DIR_GIT/n
echo "building & installing..."
cd $JRM_DIR_GIT/n
sudo chown -R $USER /usr/local/
make
sudo make install
sleep 1
echo "done! remember to install npm with e.g. 'n lts', 'n latest' etc"
sleep 3
echo "installing Rustup version manager & cargo..."
curl sh.rustup.rs -sSf | sh -s -- -y
sleep 1
echo "Rust binaries and Cargo have been installed to $HOME/cargo!"
echo "Manage Rust versions by running rustup"
sleep 1
echo "installing rbenv to manage Ruby..."
# setup rbenv, and cross fingers
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
echo "rbenv has been installed to $HOME/.rbenv"
sleep 1
echo "verifying installation..."
# verify rbenv 
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
echo "remember to first run 'rbenv install [version]' and then set it as default with"
echo "rbenv global [version]"
echo "TIP: if building ruby on a machine with less than 1gb ram, manually set"
echo "a temp directory to build from e.g."
echo "TMPDIR=~/ rbenv install 2.7.0"
echo "
  _______ __       __       __             __ __
 |   _   |__.-----|__.-----|  |--.-----.--|  |  |
 |.  1___|  |     |  |__ --|     |  -__|  _  |__|
 |.  __) |__|__|__|__|_____|__|__|_____|_____|__|
 |:  | bootrap complete - happy coding!
 |::.|        scuggscorp inc. 
 \`---'                https://ha.zardo.us
"







